import { Tab, TabList, TabPanel, Tabs } from 'react-aria-components';
import type { Schedule } from '@/domain/schedule';
import { tabletLabel } from '@/domain/schedule';
import type { ModelResult } from '@/model/pk';
import type { DerivedPeriod } from '@/interpretation/periods';
import { ExposureChart } from './ExposureChart';

export function AnalyzeView({ schedule, model, periods, selectedDoseId, onSelectDose }: { schedule: Schedule; model: ModelResult; periods: DerivedPeriod[]; selectedDoseId: string | null; onSelectDose: (id: string | null) => void }) {
  return <main className="view view--analyze" id="main-content"><header className="view-heading"><p>Technical modeled exposure</p></header><Tabs className="analyze-tabs" defaultSelectedKey="total"><TabList aria-label="Analyze layers"><Tab id="total">Total</Tab><Tab id="doses">By dose</Tab><Tab id="periods">Periods</Tab></TabList><TabPanel id="total"><ExposureChart model={model} selectedDoseId={selectedDoseId} onSelectDose={onSelectDose}/></TabPanel><TabPanel id="doses"><ExposureChart model={model} selectedDoseId={selectedDoseId} onSelectDose={onSelectDose}/></TabPanel><TabPanel id="periods"><div className="period-table">{periods.map((period)=><div key={period.id} className={`period-table__row period-table__row--${period.kind}`}><strong>{period.label}</strong><span>{period.start}–{period.end} modeled minutes</span></div>)}</div></TabPanel></Tabs><section className="analyze-dose-list" aria-labelledby="dose-list-title"><h2 id="dose-list-title">Select a dose contribution</h2>{schedule.doses.map((dose)=><button key={dose.id} className={selectedDoseId===dose.id?'analyze-dose-row is-selected':'analyze-dose-row'} onClick={()=>onSelectDose(dose.id)}><strong>{dose.time}</strong><span>{dose.mg} mg · {tabletLabel(dose)}</span></button>)}</section><details className="model-notes"><summary>Model and limitations</summary><p>The curve is a deterministic effect-site model normalized to an isolated 200 mg controlled-release dose. The 8% practical-zero transform and period labels are documented display heuristics, not clinical thresholds.</p></details></main>;
}
