import { useState } from 'react';
import { DownloadSimpleIcon, LinkSimpleIcon, MinusIcon, PlusIcon, TrashIcon } from '@phosphor-icons/react';
import type { Dose, Schedule } from '@/domain/schedule';
import { normalizeSchedule } from '@/domain/schedule';
import { Button } from '@/components/ui/Button';
import { TabletIllustration } from '@/components/icons/TabletIllustration';

export function ScheduleView({ schedule, onChange, onShare }: { schedule: Schedule; onChange: (schedule: Schedule) => void; onShare: () => void }) {
  const [draft, setDraft] = useState(schedule);
  const updateDose=(id:string,patch:Partial<Dose>)=>setDraft((current)=>({...current,doses:current.doses.map((dose)=>dose.id===id?{...dose,...patch}:dose)}));
  const save=()=>onChange(normalizeSchedule(draft));
  const add=()=>setDraft((current)=>({...current,doses:[...current.doses,{id:`dose-${Date.now()}`,time:'21:00',mg:100,formulation:'CR',tabletFraction:0.5}]}));
  const remove=(id:string)=>setDraft((current)=>current.doses.length===1?current:{...current,doses:current.doses.filter((dose)=>dose.id!==id)});
  return <main className="view view--schedule" id="main-content"><header className="view-heading view-heading--action"><div><h2>Edit schedule</h2><p>Large controls; no precision dragging.</p></div><Button variant="primary" onPress={save}>Done</Button></header><div className="editor-list">{draft.doses.map((dose)=><fieldset className="dose-editor" key={dose.id}><legend className="sr-only">Dose at {dose.time}</legend><label><span>Time</span><input type="time" value={dose.time} onChange={(event)=>updateDose(dose.id,{time:event.target.value})}/></label><label><span>Levodopa</span><div className="stepper"><Button variant="icon" aria-label={`Decrease ${dose.time} dose`} onPress={()=>updateDose(dose.id,{mg:Math.max(25,dose.mg-25)})}><MinusIcon/></Button><output>{dose.mg} mg</output><Button variant="icon" aria-label={`Increase ${dose.time} dose`} onPress={()=>updateDose(dose.id,{mg:Math.min(400,dose.mg+25)})}><PlusIcon/></Button></div></label><div className="tablet-toggle" role="group" aria-label={`Tablet form for ${dose.time}`}><Button className={dose.tabletFraction===1?'is-selected':''} onPress={()=>updateDose(dose.id,{tabletFraction:1})}><TabletIllustration className="tablet-toggle__icon"/>Whole</Button><Button className={dose.tabletFraction===0.5?'is-selected':''} onPress={()=>updateDose(dose.id,{tabletFraction:0.5})}><TabletIllustration half className="tablet-toggle__icon"/>Half</Button></div><Button variant="quiet" className="remove-dose" aria-label={`Remove dose at ${dose.time}`} onPress={()=>remove(dose.id)} isDisabled={draft.doses.length===1}><TrashIcon/>Remove</Button></fieldset>)}</div><Button className="add-dose" onPress={add}><PlusIcon/>Add another dose</Button><section className="share-entry"><div><h2>Share or export schedule</h2><p>Review exactly what the link contains.</p></div><Button variant="quiet" onPress={onShare}><LinkSimpleIcon/>Open</Button></section><Button variant="secondary" className="export-button" onPress={()=>{const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='levodopa-day-map-schedule.json';link.click();URL.revokeObjectURL(link.href);}}><DownloadSimpleIcon/>Export schedule file</Button></main>;
}
